disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_outlet
  - private_action
  - unowned_variable_capture
  - weak_delegate

excluded:
  - Pods
  - .build
  - DerivedData
  - coparent.xcodeproj
  - coparentTests
  - coparentUITests

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

force_cast: warning
force_try: warning
force_unwrapping: warning

identifier_name:
  min_length: 1
  max_length:
    warning: 50
    error: 60

reporter: "xcode" 